# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'AdamBerthomiere'


menu:
- {name: 'Qui suis-je ?', path: 'menu', url: 'Qui suis-je ?.html'}
- {name: 'Mon parcours', path: 'menu', url: 'Mon parcours.html'}
- {name: 'Mes hobbies', path: 'menu', url: 'Mes hobbies.html'}
- {name: 'Contactez-moi', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'facebook', link: 'https://www.facebook.com/adam.bth'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UCHFMRJ4v2b4VF-qfVvv60Ug?'}
- {icon: 'instagram', link: 'https://www.instagram.com/cisko.da.producer/'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}
